locale: en-US
title: Skynet Today
description: Putting AI News In Perspective
url: 
logo: site-logo-white.png
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: # 200
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
feed:
  path: feed.xml

permalink: /:categories/:title/
markdown: kramdown
search_full_content: true # can have performance implications for large sites
comments: true
show_drafts: false
future:      true
unpublished: false
mathjax: true
google_analytics: UA-54402578-2

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from  



kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  enable_coderay: false

include: [".htaccess","_pages"]
exclude: ["CNAME", "_deploy.yml", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "scripts"]

google_analytics: UA-114440651-1

owner:
  name: Andrey Kurenkov
  avatar: andrey_face.jpg
  email: andreyk@stanford.com
  web: //www.andreykurenkov.com
  disqus-shortname: skynet-today
  twitter: skynet_today

defaults:
  # Posts defaults
  - scope:
      path: "content/news/_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: "content/editorials/_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

# Footer Links
footer_links:
  - title: Feed
    url: feed.xml
    icon: fa fa-rss-square fa-2x
  - title: Twitter
    url: https://twitter.com/skynet_today
    icon: fa fa-twitter-square fa-2x
  - title: Facebook
    url: https://www.facebook.com/pg/TheSkynetToday/
    icon: fa fa-facebook-square fa-2x
